apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: iot-bonus
  namespace: argocd
spec:
  project: default
  source:
    repoURL: http://gitlab-webservice-default.gitlab.svc.cluster.local:8181/root/iot-bonus.git
    targetRevision: main
    path: manifests
  destination:
    server: https://kubernetes.default.svc
    namespace: bonus
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
